
phrases = [
    ("Ő vezeti az autót.", "Elle conduit la voiture."),
    ("Ő főzi a vacsorát.", "Il cuisine le dîner."),
    ("A nap süt az égen.", "Le soleil brille dans le ciel."),
    ("A tenger csillog a meleg sugarai alatt.", "La mer scintille sous ses rayons chauds."),
    ("A madarak örömmel énekelnek a fák között.", "Les oiseaux chantent joyeusement parmi les arbres."),
    ("A csend hangját hallom.", "J'entends le son du silence."),
    ("A boldogság az egyszerű dolgokban rejlik.", "Le bonheur réside dans les choses simples."),
    ("Az élet rövid, élvezd minden pillanatát.", "La vie est courte, profite de chaque instant."),
    ("A szerelem mindenek felett áll.", "L'amour est au-dessus de tout."),
    ("Az emberiség jövője a kezedben van.", "L'avenir de l'humanité est entre tes mains."),
    ("Az idő az egyetlen dolog, ami sosem tér vissza.", "Le temps est la seule chose qui ne revient jamais."),
    ("A múlt tapasztalatokat ad, de nem ítélkezik felette.", "Le passé donne de l'expérience, mais ne juge pas."),
    ("A jövő mindig rejtelem marad.", "Le futur reste toujours un mystère."),
    ("Az álmok valósággá válhatnak.", "Les rêves peuvent devenir réalité."),
    ("A munka értéket ad az életnek.", "Le travail donne de la valeur à la vie."),
    ("Az alázatosság erény.", "L'humilité est une vertu."),
    ("Az önbizalom kulcsfontosságú a sikerhez.", "La confiance en soi est essentielle pour réussir."),
    ("Az önbizalom vonzóvá teszi az embert.", "La confiance en soi rend une personne attrayante."),
    ("Az önbizalom bátorságot ad.", "La confiance en soi donne du courage."),
    ("Az önbizalom a belső erő forrása.", "La confiance en soi est la source de la force intérieure."),
    ("Az önbizalom az önszeretet alapja.", "La confiance en soi est la base de l'amour-propre."),
    ("Az önbizalom a pozitív gondolkodás alapja.", "La confiance en soi est la base de la pensée positive."),
    ("Az önbizalom szükséges a céljaid eléréséhez.", "La confiance en soi est nécessaire pour atteindre tes objectifs."),
    ("Az önbizalom az önbizalom egyik kulcsa.", "La confiance en soi est l'une des clés de la confiance en soi."),
    ("Az önbizalom magabiztosságot ad.", "La confiance en soi donne de l'assurance."),
    ("Az önbizalom növeli az önértékelést.", "La confiance en soi augmente l'estime de soi."),
    ("Az önbizalom javítja a kommunikációt.", "La confiance en soi améliore la communication."),
    ("Az önbizalom erősíti a kapcsolatokat.", "La confiance en soi renforce les relations."),
    ("Az önbizalom növeli a boldogságot.", "La confiance en soi augmente le bonheur."),
    ("Az önbizalom javítja az életminőséget.", "La confiance en soi améliore la qualité de vie."),
    ("Az önbizalom segít megbirkózni a kihívásokkal.", "La confiance en soi aide à relever les défis."),
    ("Az önbizalom növeli a teljesítményt.", "La confiance en soi augmente les performances."),
    ("Az önbizalom eredményekhez vezet.", "La confiance en soi conduit à des résultats."),
    ("Az önbizalom boldogságot hoz.", "La confiance en soi apporte le bonheur."),
    ("Az önbizalom növeli az önbizalmat.", "La confiance en soi augmente la confiance en soi."),
    ("Az önbizalom segít megbirkózni a stresszel.", "La confiance en soi aide à faire face au stress."),
    ("Az önbizalom megszabadít a félelemtől.", "La confiance en soi libère de la peur."),
    ("Az önbizalom segít a célok elérésében.", "La confiance en soi aide à atteindre les objectifs."),
    ("Az önbizalom erősíti a belső béke érzését.", "La confiance en soi renforce le sentiment de paix intérieure."),
    ("Az önbizalom serkenti a kreativitást.", "La confiance en soi stimule la créativité."),
    ("Az önbizalom növeli a motivációt.", "La confiance en soi augmente la motivation."),
    ("Az önbizalom segít a kudarcok kezelésében.", "La confiance en soi aide à gérer les échecs."),
    ("Az önbizalom segít túllépni a korlátokon.", "La confiance en soi aide à dépasser les limites."),
    ("Az önbizalom segít kitartani a céljaid mellett.", "La confiance en soi aide à persévérer dans tes objectifs."),
    ("Az önbizalom segít hinni önmagadban.", "La confiance en soi aide à croire en toi-même."),
    ("Az önbizalom segít elfogadni önmagadat.", "La confiance en soi aide à s'accepter soi-même."),
    ("Az önbizalom segít szeretni önmagadat.", "La confiance en soi aide à s'aimer soi-même."),
    ("Az önbizalom segít a személyes fejlődésben.", "La confiance en soi aide au développement personnel."),
    ("Az önbizalom segít a boldogság megtalálásában.", "La confiance en soi aide à trouver le bonheur."),
    ("Az önbizalom segít megtalálni az élet értelmét.", "La confiance en soi aide à trouver le sens de la vie."),
    ("Az önbizalom segít az élet örömeinek megtalálásában.", "La confiance en soi aide à trouver les joies de la vie."),
    ("Az önbizalom segít a stressz kezelésében.", "La confiance en soi aide à gérer le stress."),
    ("Az önbizalom segít az önbizalomhiány kezelésében.", "La confiance en soi aide à gérer le manque de confiance en soi."),
    ("Az önbizalom segít a kritikák kezelésében.", "La confiance en soi aide à gérer les critiques."),
    ("Az önbizalom segít a félelmek leküzdésében.", "La confiance en soi aide à surmonter les peurs."),
    ("Az önbizalom segít a depresszió leküzdésében.", "La confiance en soi aide à surmonter la dépression."),
    ("Az önbizalom segít az önbizalomhiány leküzdésében.", "La confiance en soi aide à surmonter le manque de confiance en soi."),
    ("Az önbizalom segít a szorongás leküzdésében.", "La confiance en soi aide à surmonter l'anxiété."),
    ("Az önbizalom segít az önbizalomhiány kezelésében.", "La confiance en soi aide à gérer le manque de confiance en soi."),
    ("Az önbizalom segít a stressz kezelésében.", "La confiance en soi aide à gérer le stress."),
    ("Az önbizalom segít az élet nehézségeinek leküzdésében.", "La confiance en soi aide à surmonter les difficultés de la vie."),
    ("Az önbizalom segít a kudarcok kezelésében.", "La confiance en soi aide à gérer les échecs."),
    ("Az önbizalom segít az önbizalomhiány leküzdésében.", "La confiance en soi aide à surmonter le manque de confiance en soi."),
    ("Ma reggel esik az eső.", "Ce matin, il pleut."),
    ("Holnap találkozunk.", "Nous nous rencontrons demain."),
    ("Tegnap vacsorázni mentünk.", "Hier, nous sommes allés dîner."),
    ("Hamarosan elindulunk.", "Nous partons bientôt."),
    ("Múlt héten nyaraltunk.", "La semaine dernière, nous avons été en vacances."),
    ("A jövő hétvégén bulit szervezünk.", "Le week-end prochain, nous organisons une fête."),
    ("Néhány óra múlva hazaérünk.", "Dans quelques heures, nous serons rentrés à la maison."),
    ("Nemsokára elkezdődik a film.", "Le film va commencer bientôt."),
    ("Hétfőn kezdődik az iskola.", "L'école commence lundi."),
    ("Vasárnap találkozunk.", "Nous nous retrouvons dimanche."),
    ("Péntek van, a hétvége közeleg.", "C'est vendredi, le week-end approche."),
    ("Kedden dolgozom.", "Je travaille mardi."),
    ("Szombaton utazom.", "Je voyage samedi."),
    ("Csütörtök van, a hét közepe.", "C'est jeudi, le milieu de la semaine."),
    ("Szerdán találkozunk.", "Nous nous rencontrons mercredi."),
    ("A múlt hónapban sokat dolgoztam.", "Le mois dernier, j'ai beaucoup travaillé."),
    ("A jövő hónapban nyaralni megyek.", "Le mois prochain, je pars en vacances."),
    ("Az elmúlt évben sokat tanultam.", "L'année dernière, j'ai beaucoup appris."),
    ("A jövő évben új dolgokat tanulok.", "L'année prochaine, j'apprends de nouvelles choses."),
    ("Egy órája dolgozom.", "Je travaille depuis une heure."),
    ("Két órája tanulok.", "J'étudie depuis deux heures."),
    ("Három órája alszom.", "Je dors depuis trois heures."),
    ("Öt perce esik az eső.", "Il pleut depuis cinq minutes."),
    ("Tíz perce várok rád.", "J'attends depuis dix minutes."),
    ("Húsz perce telefonálok.", "Je téléphone depuis vingt minutes."),
    ("Egy órája olvasok.", "Je lis depuis une heure."),
    ("Két órája tanulok.", "J'étudie depuis deux heures."),
    ("Három órája sétálok.", "Je me promène depuis trois heures."),
    ("Tíz perce dolgozom.", "Je travaille depuis dix minutes."),
    ("Húsz perce főzök.", "Je cuisine depuis vingt minutes."),
    ("Egy órája sportolok.", "Je fais du sport depuis une heure."),
    ("Két órája nézek tévét.", "Je regarde la télévision depuis deux heures."),
    ("Három órája dolgozom.", "Je travaille depuis trois heures."),
    ("Tíz perce olvasok.", "Je lis depuis dix minutes."),
    ("Húsz perce tanulok.", "J'étudie depuis vingt minutes."),
    ("Egy órája pihenek.", "Je me repose depuis une heure."),
    ("Két órája sétálok.", "Je me promène depuis deux heures."),
    ("Három órája várakozom.", "J'attends depuis trois heures."),
    ("Tíz perce dolgozom.", "Je travaille depuis dix minutes."),
    ("Húsz perce sütök.", "Je cuisine depuis vingt minutes."),
    ("Egy órája sütögetek.", "Je fais des gâteaux depuis une heure."),
    ("Két órája futok.", "Je cours depuis deux heures."),
    ("Három órája utazom.", "Je voyage depuis trois heures."),
    ("Tíz perce játszom.", "Je joue depuis dix minutes."),
    ("Húsz perce hallgatom a zenét.", "J'écoute de la musique depuis vingt minutes."),
    ("Egy órája szörfözök.", "Je fais du surf depuis une heure."),
    ("Két órája festek.", "Je peins depuis deux heures."),
    ("Három órája vezetek.", "Je conduis depuis trois heures."),
    ("Tíz perce beszélek veled.", "Je te parle depuis dix minutes."),
    ("Húsz perce edzek.", "Je m'entraîne depuis vingt minutes."),
    ("Egy órája táncolok.", "Je danse depuis une heure."),
    ("Két órája szurkolok.", "Je soutiens depuis deux heures."),
    ("Három órája pihenek.", "Je me repose depuis trois heures."),
    ("Tíz perce esik az eső.", "Il pleut depuis dix minutes."),
    ("Húsz perce fúj a szél.", "Il vente depuis vingt minutes."),
    ("Egy órája szakad az eső.", "Il pleut à verse depuis une heure."),
    ("Két órája havazik.", "Il neige depuis deux heures."),
    ("Három órája napozom.", "Je prends un bain de soleil depuis trois heures."),
    ("Tíz perce olvastok.", "Vous lisez depuis dix minutes."),
    ("Húsz perce táncoltok.", "Vous dansez depuis vingt minutes."),
    ("Egy órája főztök.", "Vous cuisinez depuis une heure."),
    ("Két órája tanultok.", "Vous étudiez depuis deux heures."),
    ("Három órája dolgoztok.", "Vous travaillez depuis trois heures."),
    ("Tíz perce tanulnak.", "Ils étudient depuis dix minutes."),
    ("Húsz perce dolgoznak.", "Ils travaillent depuis vingt minutes."),
    ("Egy órája olvasnak.", "Ils lisent depuis une heure."),
    ("Két órája beszélgetnek.", "Ils discutent depuis deux heures."),
    ("Három órája edzenek.", "Ils s'entraînent depuis trois heures."),
    ("Tíz perce esik az eső.", "Il pleut depuis dix minutes."),
    ("Húsz perce fúj a szél.", "Il vente depuis vingt minutes."),
    ("Egy órája szakad az eső.", "Il pleut à verse depuis une heure."),
    ("Két órája havazik.", "Il neige depuis deux heures."),
    ("Három órája napozom.", "Je prends un bain de soleil depuis trois heures."),
    ("Tíz perce olvastok.", "Vous lisez depuis dix minutes."),
    ("Húsz perce táncoltok.", "Vous dansez depuis vingt minutes."),
    ("Egy órája főztök.", "Vous cuisinez depuis une heure."),
    ("Két órája tanultok.", "Vous étudiez depuis deux heures."),
    ("Három órája dolgoztok.", "Vous travaillez depuis trois heures."),
    ("Tíz perce tanulnak.", "Ils étudient depuis dix minutes."),
    ("Húsz perce dolgoznak.", "Ils travaillent depuis vingt minutes."),
    ("Egy órája olvasnak.", "Ils lisent depuis une heure."),
    ("Két órája beszélgetnek.", "Ils discutent depuis deux heures."),
    ("Három órája edzenek.", "Ils s'entraînent depuis trois heures."),
    ("Ő vezeti az autót.", "Elle conduit la voiture."),
    ("Ő főzi a vacsorát.", "Il cuisine le dîner."),
    ("Ő megjavítja a vízvezetéket.", "Elle répare la plomberie."),
    ("Ő vasalja a ruhákat.", "Il repasse les vêtements."),
    ("Ő épít egy házat.", "Elle construit une maison."),
    ("Ő varr egy ruhadarabot.", "Il coud un vêtement."),
    ("Ő telepít polcokat.", "Elle installe des étagères."),
    ("Ő festi a falakat.", "Il peint les murs."),
    ("Ő nyírja a füvet.", "Elle tond la pelouse."),
    ("Ő megjavítja az autót.", "Il répare la voiture."),
    ("Ő programoz egy szoftvert.", "Elle programme un logiciel."),
    ("Ő díszíti a házat.", "Il décore la maison."),
    ("Ő metszi a sövényeket.", "Elle taille les haies."),
    ("Ő tisztítja az ablakokat.", "Il nettoie les vitres."),
    ("Ő karbantartja a kertet.", "Elle entretient le jardin."),
    ("Ő locsolja a növényeket.", "Il arrose les plantes."),
    ("Ő felújítja a konyhát.", "Elle rénove la cuisine."),
    ("Ő összeszereli a bútorokat.", "Il assemble les meubles."),
    ("Ő pakolja a dobozokat.", "Elle déménage les cartons."),
    ("Ő mos ruhát.", "Il fait la lessive."),
    ("Ő borotválja a szakállát.", "Elle tond la barbe."),
    ("Ő gyomlálja a kertet.", "Il désherbe le jardin."),
    ("Ő rajzol egy portrét.", "Elle dessine un portrait."),
    ("Ő farag egy szobrot.", "Il sculpte une statue."),
    ("Ő fényképez egy tájat.", "Elle photographie le paysage."),
    ("Ő ír egy dalt.", "Il compose une chanson."),
    ("Ő ír egy regényt.", "Elle écrit un roman."),
    ("Ő rendez egy filmet.", "Il réalise un film."),
    ("Ő játszik egy hangszeren.", "Elle joue d'un instrument."),
    ("Ő zsonglőrködik labdákkal.", "Il jongle avec des balles."),
    ("Ő zsonglőrködik gyertyatartókkal.", "Elle jongle avec des quilles."),
    ("Ő zsonglőrködik gyűrűkkel.", "Il jongle avec des anneaux."),
    ("Ő egy kötélen jár.", "Elle marche sur un fil."),
    ("Ő akrobatikázik.", "Il fait des acrobaties."),
    ("Ő salsázik.", "Elle danse la salsa."),
    ("Ő énekel egy dalt.", "Il chante une chanson."),
    ("Ő teniszezik.", "Elle joue au tennis."),
    ("Ő focizik.", "Il joue au football."),
    ("Ő úszik a medencében.", "Elle nage dans la piscine."),
    ("Ő fut a pályán.", "Il court sur la piste."),
    ("Ő ugrál a kötélen.", "Elle saute à la corde."),
    ("Ő dob egy diszkoszt.", "Il lance un disque."),
    ("Ő ír egy regényt.", "Elle écrit un roman."),
    ("Ő elkészíti a tortát.", "La pâtissière fait un gâteau."), 
    ("Ő összefogja a deszkákat.", "Elle cloue des planches ensemble."), 
    ("Ő hidratáló krémet használ.", "Il utilise une crème hydratante."),
    ("Zongorázik.", "Elle joue du piano."),
    ("Kertészkedik.", "Il fait du jardinage."),
    ("Tájképet rajzol.", "Elle dessine un paysage."),
    ("Verseket ír.", "Il écrit des poèmes."),
    ("Süteményeket süt.", "Elle cuisine des pâtisseries."),
    ("Szobrokat farag.", "Il sculpte des sculptures."),
    ("Önkénteskedik.", "Elle fait du bénévolat."),
    ("Meditál.", "Il pratique la méditation."),
    ("Festményeket fest.", "Elle peint des tableaux."),
    ("Színházban játszik.", "Il fait du théâtre.")
]